
















### Prueba de vida
get http://localhost:3000/


### Signup - Crear nuevo usuario
POST http://localhost:3000/api/v1/signup
Content-Type: application/json

{
  "name": "Roberto Carlos Quinto",
  "email": "roberto5@example.com",
  "password": "12345678",
  "phone": "1234567890"
}

### Login - Login usuario
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "email": "roberto3@example.com",
  "password": "12345678"
}
# > {% 
# // Parseamos JSON y guardamos token globalmente
# const body = response.json(); 
# client.global.set("token", body.token); 
# %}


### New Category - Crear nueva categoria
POST http://localhost:3000/api/v1/categories HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGQ4YTMxODcwNDI3ODFlYmJmMmExNSIsImVtYWlsIjoicm9iZXJ0bzNAZXhhbXBsZS5jb20iLCJyb2xlIjpbImN1c3RvbWVyIl0sImlhdCI6MTc1OTQ0MjU5NSwiZXhwIjoxNzU5NDQ2MTk1fQ.FsYjMo7jtCrvoO0htb6ArtkBn7Z7U97EE5y_6J_Zp4U

{
    "name": "categoria prueba 2 postman"
}



